### ISSUE TITLE
Add test suite for conversion from YAML to ARM 

### ISSUE THREAD

**Issue by Manbearpiet** [f-bader/SentinelARConverter#24]
### Summary of the new feature / enhancement

As a user 
I want to have more confidence that my ART YAML will convert in a deployable format
So that I can convert and deploy my YAML stored content confidently

**Comment by f-bader** [comment]
Added initial set of tests including function tests aimed at new version released in #26 

https://github.com/f-bader/SentinelARConverter/blob/main/tests/Convert-SentinelARYamlToArm.tests.ps1
