### ISSUE TITLE
Piping Convert-SentinelARArmToYaml with Get-Content does not work

### ISSUE THREAD

**Issue by tobiasmoee** [f-bader/SentinelARConverter#34]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/SentinelARConverter/)
- [X] Search the existing issues.

### Steps to reproduce

Download YAML analytical rule from[ Azure-Sentinel repo ](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/AccountCreatedDeletedByNonApprovedUser.yaml).
Convert file to ARM.
Convert file back to YAML using **Get-Content ".\AccountCreatedDeletedByNonApprovedUser.json" | Convert-SentinelARArmToYaml** 

**Convert-SentinelARArmToYaml -Filename ".\AccountCreatedDeletedByNonApprovedUser.json"** works as expected.
**Get-Content ".\AccountCreatedDeletedByNonApprovedUser.yaml" | Convert-SentinelARYamlToArm** works as expected.

Also replicated the same issue on powershell 7.4.2

### Expected behavior

```console
PS> Get-Content ".\AccountCreatedDeletedByNonApprovedUser.json" | Convert-SentinelARArmToYaml

I expected this line to paste content of AccountCreatedDeletedByNonApprovedUser in stdout in yaml format
```

### Actual behavior

```console
PS> Get-Content ".\AccountCreatedDeletedByNonApprovedUser.json" | Convert-SentinelARArmToYaml
Could not convert source file. JSON might be corrupted
At C:\Program Files\WindowsPowerShell\Modules\SentinelARConverter\2.2.4\public\Convert-SentinelARArmToYaml.ps1:210 char:13
+             throw "Could not convert source file. JSON might be corru ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not conve...ht be corrupted:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not convert source file. JSON might be corrupted
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![Screenshot 2024-04-17 141050](https://github.com/f-bader/SentinelARConverter/assets/157579648/d83e84fd-8e1f-47d5-a7db-2f56466695d0)

**Comment by Konverto-MartinGasser** [comment]
It should work when you pass the content as -raw
![image](https://github.com/f-bader/SentinelARConverter/assets/131176668/a32c2695-167f-4c0d-b9ef-e8baf3903601)

**Comment by f-bader** [comment]
As @Konverto-MartinGasser correctly pointed out you have to use -raw parameter. 

This is because the Get-Content cmdlet otherwise will send the file line by line, which in turn results in validation errors 

I'm closing this issue, if you have any other questions, feel free to comment or create a separate issue
